// <auto-generated />
using System;
using DefenceSimulator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DefenceSimulator.Migrations
{
    [DbContext(typeof(DefenceSimulatorContext))]
    partial class DefenceSimulatorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DefenceSimulator.Models.DefenceWeapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DefenceWeapon");
                });

            modelBuilder.Entity("DefenceSimulator.Models.Enemy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Distance")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Enemy");
                });

            modelBuilder.Entity("DefenceSimulator.Models.Response", b =>
                {
                    b.Property<int>("ResponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResponseId"));

                    b.Property<DateTime?>("InterceptTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LaunchTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("SalvoId")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("ResponseId");

                    b.HasIndex("SalvoId");

                    b.ToTable("Response");
                });

            modelBuilder.Entity("DefenceSimulator.Models.Salvo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EnemyId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LaunchTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("WeaponAmount")
                        .HasColumnType("int");

                    b.Property<int>("WeaponId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnemyId");

                    b.HasIndex("WeaponId");

                    b.ToTable("Salvo");
                });

            modelBuilder.Entity("DefenceSimulator.Models.Weapon", b =>
                {
                    b.Property<int>("WeaponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeaponId"));

                    b.Property<int?>("DefenceWeaponId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.HasKey("WeaponId");

                    b.HasIndex("DefenceWeaponId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Weapon");
                });

            modelBuilder.Entity("DefenceSimulator.Models.Response", b =>
                {
                    b.HasOne("DefenceSimulator.Models.Salvo", "salvo")
                        .WithMany("Responses")
                        .HasForeignKey("SalvoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("salvo");
                });

            modelBuilder.Entity("DefenceSimulator.Models.Salvo", b =>
                {
                    b.HasOne("DefenceSimulator.Models.Enemy", "Enemy")
                        .WithMany("Salvo")
                        .HasForeignKey("EnemyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DefenceSimulator.Models.Weapon", "Weapon")
                        .WithMany()
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enemy");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("DefenceSimulator.Models.Weapon", b =>
                {
                    b.HasOne("DefenceSimulator.Models.DefenceWeapon", "DefenceWeapon")
                        .WithMany("Weapons")
                        .HasForeignKey("DefenceWeaponId");

                    b.Navigation("DefenceWeapon");
                });

            modelBuilder.Entity("DefenceSimulator.Models.DefenceWeapon", b =>
                {
                    b.Navigation("Weapons");
                });

            modelBuilder.Entity("DefenceSimulator.Models.Enemy", b =>
                {
                    b.Navigation("Salvo");
                });

            modelBuilder.Entity("DefenceSimulator.Models.Salvo", b =>
                {
                    b.Navigation("Responses");
                });
#pragma warning restore 612, 618
        }
    }
}
